version: '3.4'

#networks:
networks:
  dev:
    driver: bridge

services:
  demo-app:
    image: docker.io/library/hulk-api
    depends_on:
      - "app_db"
    container_name: demoapp-services
    ports:
      - "8085:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=app_db;Port=5432;Database=PocDb;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev

  # fargate
  # test:
  #   image: imageName

  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SimpleDb
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  app_data: